<?php

namespace modules\entrant\modules\ones\model;
use yii\db\ActiveRecord;

/**
 * @property int $id
 * @property string $department
 * @property string $education_level
 * @property string $type_competitive
 *
 */
class OrderTransferOnes extends ActiveRecord
{
    public static function tableName(): string
    {
        return '{{%order_transfer_ones}}';
    }

    public function afterFind()
    {
        parent::afterFind(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        $this->education_level = json_encode($this->education_level, JSON_UNESCAPED_UNICODE);
        $this->type_competitive = json_encode($this->type_competitive, JSON_UNESCAPED_UNICODE);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            [['department', 'education_level','type_competitive'], 'required'],
            [['department'], 'string'],
            [['education_level', 'type_competitive'], 'safe'],
        ];
    }

    public function attributeLabels(): array
    {
        return [
            'education_level' => "Уровни образования",
            'department' => "Факультет/Филиал",
            'type_competitive' => "Виды мест",
        ];
    }
    /**
     * @return string
     */
    public function getEducationLevelName()
    {
        return implode(', ', json_decode($this->education_level));
    }
    /**
     * @return string
     */
    public function getTypeName()
    {
        return implode(', ', json_decode($this->type_competitive));
    }

    public static function allEduLevels() {
        $data = CompetitiveGroupOnes::find()->select('education_level')->indexBy('education_level')->column();
        return $data;
    }

    public static function allTypes() {
        $data = CompetitiveGroupOnes::find()->select('type_competitive')->indexBy('type_competitive')->column();
        return $data;
    }

    public static function allDepartments() {
        $data = CompetitiveGroupOnes::find()->select('department')->indexBy('department')->column();
        return $data;
    }
}
