<?php


namespace common\components;


use yii\base\Component;
use Yii;
use yii\base\InvalidConfigException;

class Mailer extends Component
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function mailer () {
        return Yii::createObject([
            'class' => 'yii\swiftmailer\Mailer',
            'viewPath' => '@common/mail',
            'transport' => [
                'class' => 'Swift_SmtpTransport',
                'host' => 'smtp.gmail.com',
                'username' => 'cpk@mpgu.edu',
                'password' => 'w5h38c4v',
                'port' => '465',
                'encryption' => 'ssl',
            ],
        ]);
    }


}