<?php


namespace modules\superservice;


use yii\base\Application;
use yii\base\BootstrapInterface;
use yii\base\Module;

class SuperService extends Module implements BootstrapInterface
{
    public $controllerNamespace = 'modules\superservice\controllers\amqp';

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * Bootstrap method to be called during application bootstrap stage.
     * @param Application $app the application currently running
     */
    public function bootstrap($app)
    {
        if ($app instanceof \yii\console\Application) {
            $this->controllerNamespace = 'modules\superservice\controllers';
        }
    }
}