<?php namespace common\tests;

use dictionary\forms\DictClassCreateForm;
use dictionary\helpers\DictClassHelper;

class dictClassFromTest extends beforeTest
{
    /**
     * @var \common\tests\UnitTester
     */
    protected $tester;

    protected function _before()
    {
        $this->dataFixture();
        parent::_before(); // TODO: Change the autogenerated stub
    }

    protected function _after()
    {
    }

    // tests
    public function testValidateEmptyNameForm()
    {
        $model = new DictClassCreateForm();
        $model->name = "";
        $model->type = DictClassHelper::SCHOOL;
        $this->assertFalse($model->validate());

    }

    public function testValidateEmptyTypeForm()
    {
        $model = new DictClassCreateForm();
        $model->name = 1;
        $model->type = "";
        $this->assertFalse($model->validate());

    }
}