<?php
    return [
        'name' => 'Межрегиональный академический очный конкурс учебного наброска',
        'chairman_id' => 1,
        'number_of_tours' => 1,
        'form_of_passage' => 1,
        'edu_level_olymp' => 1,
        'date_time_start_reg' => '2019-11-15 12:00:00',
        'date_time_finish_reg' => '2019-12-07 12:00:00',
        'time_of_distants_tour' => NULL,
        'date_time_start_tour' => '2019-12-07 12:00:00',
        'address' => 'г. Москва, Рязанский проспект д.9',
        'time_of_tour' => 90,
        'requiment_to_work_of_distance_tour' => 'Требование к выполнению работ заочного (дистанционного) тура',
        'requiment_to_work' => 'Требование к выполнению работ очного тура',
        'criteria_for_evaluating_dt' => 'Критерии оценивания работ заочного (дистанционного) тура',
        'criteria_for_evaluating' => 'Критерии оценивания работ очного тура',
        'showing_works_and_appeal' => 0,
        'genitive_name' => 'Межрегионального академического очного конкурса учебного наброска',
        'time_of_distants_tour_type' => NULL,
        'prefilling' => 0,
        'faculty_id' => 1,
        'only_mpgu_students' => 0,
        'promotion_text' => 'Рекламный текст, который будет завлекать участников',
        'link' => 'Ссылка на страницу регистрации (для олимпиад, которые не проводятся на нашем сайте)',
        'list_position' => NULL,
        'content' => 'Аннотация на главную страницу олимпиады',
        'required_documents' => 'Необходимые документы на очный тур',
        'year' => '2019-2020',
        'certificate_id' => 1,
    ];
