FROM php:7.4-fpm-alpine

RUN apk add --update --no-cache libgd libzip-dev libpng-dev libjpeg-turbo-dev freetype-dev

RUN docker-php-ext-install -j$(nproc) gd && \
    docker-php-ext-install pdo_mysql zip sockets && \
    docker-php-ext-enable sockets

ADD php.ini /usr/local/etc/php.ini