<?php


namespace modules\dictionary\services;


use modules\dictionary\helpers\TestingEntrantHelper;
use modules\dictionary\models\DictTestingEntrant;
use modules\dictionary\models\TestingEntrantDict;
use modules\dictionary\repositories\DictTestingEntrantRepository;
use modules\usecase\ServicesClass;


class DictTestingEntrantService extends ServicesClass
{

    public function __construct(DictTestingEntrantRepository $repository, DictTestingEntrant $model)
    {
        $this->repository = $repository;
        $this->model = $model;
    }

    public function remove($id)
    {
       if(TestingEntrantDict::find()->andWhere(['id_dict_testing_entrant'=>$id])->exists()) {
           throw  new \DomainException("Вы не можете удалить подзадачу, так как она существует в задачах для волонтеров");
       }
        parent::remove($id); // TODO: Change the autogenerated stub
    }

}