FROM php:7.2

RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip smbclient \
    libicu-dev libxml2-dev libsmbclient-dev libldap2-dev libzip-dev libpng-dev libfreetype6-dev libjpeg62-turbo-dev && \
    ln -fs /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/

RUN docker-php-ext-install pdo_mysql mbstring intl zip xml fileinfo opcache ldap && \
    docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ && \
    docker-php-ext-install gd && \
    pecl install smbclient && \
    pecl install xdebug && \
    pecl install dbase && \
    docker-php-ext-enable smbclient xdebug dbase

RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer

WORKDIR /app