FROM php:7.4

RUN apt-get update && \
    apt-get install -y --no-install-recommends unzip smbclient \
    libicu-dev libxml2-dev libsmbclient-dev libldap2-dev libzip-dev libpng-dev libfreetype6-dev libjpeg62-turbo-dev && \
    ln -fs /usr/lib/x86_64-linux-gnu/libldap.so /usr/lib/

RUN docker-php-ext-install -j$(nproc) gd && \
 docker-php-ext-install pdo_mysql zip sockets && \
    docker-php-ext-enable sockets

RUN curl -sS https://getcomposer.org/installer | \
    php -- --install-dir=/usr/bin/ --filename=composer

WORKDIR /app